import { Prop } from '@nestjs/mongoose';
import { Exclude } from 'class-transformer';

import { BaseEntity } from './base.entity';

export class BaseMongooseEntity implements BaseEntity {
  /**
   * Generated by src/common/constants/mongoose.constants.ts baseMongooseSchemaOptions.id = true
   */
  id: string;

  /**
   * Generated by src/common/constants/mongoose.constants.ts baseMongooseSchemaOptions.timestamps = true
   */
  createdAt: Date;

  /**
   * Generated by src/common/constants/mongoose.constants.ts baseMongooseSchemaOptions.timestamps = true
   */
  updatedAt: Date;

  /**
   * Generated by mongoose and excluded by src/common/interceptors/class-serializer.interceptor.ts
   */
  @Exclude()
  _id: string;

  /**
   * Generated by mongoose and excluded by src/common/interceptors/class-serializer.interceptor.ts
   */
  @Exclude()
  __v: number;

  /**
   * Property to implement soft delete
   */
  @Prop({ type: Date })
  deletedAt: Date | null;
}
