version: '3'

services:
  postgresql:
    container_name: habits-api_postgresql
    image: bitnami/postgresql:15.1.0
    ports:
      - ${POSTGRESQL_PORT_LOCAL}:${POSTGRESQL_PORT_DOCKER}
    volumes:
      - habits-api_postgresql_volume:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}

  redis:
    container_name: habits-api_redis
    image: redis:7.0.7
    ports:
      - ${REDIS_PORT_LOCAL}:${REDIS_PORT_DOCKER}
    command: >
      --requirepass ${REDIS_PASSWORD}

volumes:
  habits-api_postgresql_volume:
