apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl }}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${{ values.url }}
      title: API entrypoint
      icon: api
spec:
  owner: backend-devs
  type: service
  lifecycle: development
